[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#07111F"
secondaryBackgroundColor = "#101C2C"
textColor = "#E6EEF8"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
runOnSave = true
